server:
  port: 6060

spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: elasticsearch:9300
      repositories:
        enabled: true
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
    port: 5672
    #    virtual-host: /hello
    publisher-confirms: true #开启消息确认机制
    publisher-returns: true #支持消息发送失败返回队列
    template:
      mandatory: true #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除
    listener:
      simple:
        acknowledge-mode: manual #开启手动消息确认
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
        concurrency: 1
        max-concurrency: 1