# yaml 配置实例
version: '3'
services:
  demo:
    ports:
      - "6060:6060"
    image: es-test:latest
    links:
      - redis:redis
      - rabbitmq:rabbitmq
      - elasticsearch:elasticsearch
  redis:
    image: redis:3.2
    container_name: redis-es-test
    command: redis-server --appendonly yes
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq-es-test
  elasticsearch:
    image: elasticsearch:6.4.3
    container_name: elasticsearch-es-test
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
